const playerNames = [
    "Aaron MOOY",
    "ABDALLA SAID",
    "Abdiel ARROYO",
    "Abdoulaye DIALLO",
    "ABDULLAH ALKHAIBARI",
    "ABDULLAH ALMUAIOUF",
    "ABDULLAH OTAYF",
    "Abdullahi SHEHU",
    "ABDULMALEK ALKHAIBRI",
    "Abel AGUILAR",
    "Achraf HAKIMI",
    "Adama MBENGUE",
    "Adem LJAJIC",
    "Adil RAMI",
    "Adnan JANUZAJ",
    "Adolfo MACHADO",
    "ADRIEN SILVA",
    "AHMED ELMOHAMADY",
    "AHMED FATHI",
    "AHMED HEGAZY",
    "Ahmed KHALIL",
    "Ahmed MUSA",
    "Ahmed TAGNAOUTI",
    "Alan DZAGOEV",
    "Albert GUDMUNDSSON",
    "Alberto RODRIGUEZ",
    "Albin EKDAL",
    "Aldo CORZO",
    "Aleksandar KOLAROV",
    "Aleksandar MITROVIC",
    "Aleksandar PRIJOVIC",
    "Aleksandr EROKHIN",
    "Aleksandr GOLOVIN",
    "Alex IWOBI",
    "Alex RODRIGUEZ",
    "Alexander SAMEDOV",
    "Alexey MIRANCHUK",
    "Alfred FINNBOGASON",
    "Alfred GOMIS",
    "Alfred NDIAYE",
    "Alfredo TALAVERA",
    "ALI ALBULAYHI",
    "Ali BEIRANVAND",
    "ALI GABR",
    "Ali MAALOUL",
    "Alireza JAHANBAKHSH",
    "ALISSON",
    "Alphonse AREOLA",
    "Alvaro ODRIOZOLA",
    "Amine HARIT",
    "Amir ABEDZADEH",
    "AMR WARDA",
    "Anderson SANTAMARIA",
    "Andre CARRILLO",
    "ANDRE SILVA",
    "Andreas CHRISTENSEN",
    "Andreas CORNELIUS",
    "Andreas GRANQVIST",
    "Andrei LUNEV",
    "Andrej KRAMARIC",
    "Andres GUARDADO",
    "Andres INIESTA",
    "Andrew NABBOUT",
    "Andrey SEMENOV",
    "Andrija ZIVKOVIC",
    "Andy POLO",
    "Angel DI MARIA",
    "Anibal GODOY",
    "Anice BADRI",
    "Ante REBIC",
    "ANTHONY LOPES",
    "Antoine GRIEZMANN",
    "Anton MIRANCHUK",
    "Antonio RUEDIGER",
    "Antonio RUKAVINA",
    "Ari SKULASON",
    "Arkadiusz MILIK",
    "Armando COOPER",
    "Arnor TRAUSTASON",
    "Aron GUNNARSSON",
    "Artem DZYUBA",
    "Artur JEDRZEJCZYK",
    "Ashkan DEJAGAH",
    "Ashley  YOUNG",
    "Axel WITSEL",
    "AYMAN ASHRAF",
    "Aymen MATHLOUTHI",
    "Ayoub EL KAABI",
    "Aziz BEHICH",
    "Aziz BOUHADDOUZ",
    "Bartosz BERESZYNSKI",
    "Bartosz BIALKOWSKI",
    "Bassem SRARFI",
    "Benjamin MENDY",
    "Benjamin PAVARD",
    "BERNARDO SILVA",
    "BETO",
    "Birkir BJARNASON",
    "Birkir SAEVARSSON",
    "Bjorn SIGURDARSON",
    "Blaise MATUIDI",
    "Blas PEREZ",
    "Blerim DZEMAILI",
    "Brad JONES",
    "Branislav IVANOVIC",
    "Breel EMBOLO",
    "BRUNO ALVES",
    "BRUNO FERNANDES",
    "Bryan IDOWU",
    "Bryan OVIEDO",
    "Bryan RUIZ",
    "Camilo VARGAS",
    "Carlos BACCA",
    "Carlos CACEDA",
    "Carlos SALCEDO",
    "Carlos SANCHEZ",
    "Carlos SANCHEZ",
    "Carlos VELA",
    "CASEMIRO",
    "CASSIO",
    "CEDRIC",
    "Celso BORGES",
    "Cesar AZPILICUETA",
    "Cheikh NDOYE",
    "Cheikhou KOUYATE",
    "Chidozie AWAZIEM",
    "Christian BOLANOS",
    "Christian CUEVA",
    "Christian ERIKSEN",
    "Christian RAMOS",
    "Corentin TOLISSO",
    "Cristhian STUANI",
    "Cristian ANSALDI",
    "Cristian GAMBOA",
    "Cristian PAVON",
    "Cristian RODRIGUEZ",
    "Cristian ZAPATA",
    "CRISTIANO RONALDO",
    "Daler KUZIAEV",
    "Dani CARVAJAL",
    "Daniel AKPEYI",
    "Daniel ARZANI",
    "Daniel COLINDRES",
    "Danijel SUBASIC",
    "DANILO",
    "Danny ROSE",
    "Danny VUKOVIC",
    "Danny WELBECK",
    "David DE GEA",
    "David GUZMAN",
    "David OSPINA",
    "David SILVA",
    "Davinson SANCHEZ",
    "Dawid KOWNACKI",
    "Dedryck BOYATA",
    "Dejan LOVREN",
    "Dele ALLI",
    "Denis CHERYSHEV",
    "Denis ZAKARIA",
    "Diafra SAKHO",
    "Diego COSTA",
    "Diego GODIN",
    "Diego LAXALT",
    "Dimitrios PETRATOS",
    "Djibril SIDIBE",
    "Domagoj VIDA",
    "Dominik LIVAKOVIC",
    "DOUGLAS COSTA",
    "Dries MERTENS",
    "Duje CALETA-CAR",
    "Dusan TADIC",
    "Dusko TOSIC",
    "Dylan BRONN",
    "Eden HAZARD",
    "EDERSON",
    "Edgar BARCENAS",
    "Edinson CAVANI",
    "Edison FLORES",
    "Edson ALVAREZ",
    "Eduardo SALVIO",
    "Ehsan HAJI SAFI",
    "Eiji KAWASHIMA",
    "Elderson ECHIEJILE",
    "Ellyes SKHIRI",
    "Emil FORSBERG",
    "Emil HALLFREDSSON",
    "Emil KRAFTH",
    "Enzo PEREZ",
    "Eric  DIER",
    "Eric DAVIS",
    "Erick GUTIERREZ",
    "ESSAM ELHADARY",
    "Ever BANEGA",
    "Fabian DELPH",
    "Fabian SCHAER",
    "FAGNER",
    "FAHAD ALMUWALLAD",
    "Fakhreddine BEN YOUSSEF",
    "Farid DIAZ",
    "Farouk BEN MUSTAPHA",
    "Faycal FAJR",
    "Federico FAZIO",
    "Fedor KUDRIASHOV",
    "Fedor SMOLOV",
    "Felipe BALOY",
    "Ferjani SASSI",
    "FERNANDINHO",
    "Fernando MUSLERA",
    "Fidel ESCOBAR",
    "Filip BRADARIC",
    "Filip HELANDER",
    "Filip KOSTIC",
    "FILIPE LUIS",
    "Florian THAUVIN",
    "Francis UZOHO",
    "Francisco CALVO",
    "Franco ARMANI",
    "Francois MOUBANDJE",
    "FRED",
    "Frederik RONNOW",
    "Frederik SCHRAM",
    "Gabriel GOMEZ",
    "GABRIEL JESUS",
    "Gabriel MERCADO",
    "Gabriel TORRES",
    "Gaku SHIBASAKI",
    "Gary CAHILL",
    "Gaston SILVA",
    "Gelson FERNANDES",
    "GELSON MARTINS",
    "Gen SHOJI",
    "Genki HARAGUCHI",
    "Gerard PIQUE",
    "Ghanem SAISS",
    "Ghaylen CHAALELI",
    "Giancarlo GONZALEZ",
    "Giorgian DE ARRASCAETA",
    "Giovani DOS SANTOS",
    "Giovani LO CELSO",
    "GO Yohan",
    "GONCALO GUEDES",
    "Gonzalo HIGUAIN",
    "Gotoku SAKAI",
    "Granit XHAKA",
    "Grzegorz KRYCHOWIAK",
    "Guillermo OCHOA",
    "Guillermo VARELA",
    "Gustav SVENSSON",
    "Gylfi SIGURDSSON",
    "Hakim ZIYACH",
    "Hamdi NAGUEZ",
    "Hamza MENDYL",
    "Hannes HALLDORSSON",
    "Haris SEFEROVIC",
    "Harold CUMMINGS",
    "Harry KANE",
    "Harry MAGUIRE",
    "HATAN BAHBRI",
    "Hector HERRERA",
    "Hector MORENO",
    "Henrik DALSGAARD",
    "Hiroki SAKAI",
    "Hirving  LOZANO",
    "Holmar EYJOLFSSON",
    "HONG Chul",
    "Hordur MAGNUSSON",
    "Hotaru YAMAGUCHI",
    "Hugo AYALA",
    "Hugo LLORIS",
    "HUSSAIN ALMOQAHWI",
    "HWANG Heechan",
    "Iago ASPAS",
    "Ian SMITH",
    "Idrissa Gana GUEYE",
    "Igor AKINFEEV",
    "Igor SMOLNIKOV",
    "Ikechukwu EZENWA",
    "Ilkay GUENDOGAN",
    "Ilya KUTEPOV",
    "Isaac Kiese THELIN",
    "ISCO",
    "Ismael DIAZ",
    "Ismaila SARR",
    "Iury GAZINSKY",
    "Ivan PERISIC",
    "Ivan RAKITIC",
    "Ivan STRINIC",
    "Jacek GORALSKI",
    "Jack BUTLAND",
    "Jackson IRVINE",
    "Jaime PENEDO",
    "Jakub BLASZCZYKOWSKI",
    "James MEREDITH",
    "James RODRIGUEZ",
    "Jamie MacLAREN",
    "Jamie VARDY",
    "Jan BEDNAREK",
    "Jan VERTONGHEN",
    "JANG Hyunsoo",
    "Jannik VESTERGAARD",
    "Javier AQUINO",
    "Javier HERNANDEZ",
    "Javier MASCHERANO",
    "Jefferson  LERMA",
    "Jefferson FARFAN",
    "Jens Stryger LARSEN",
    "Jerome BOATENG",
    "Jesse  LINGARD",
    "Jesus CORONA",
    "Jesus GALLARDO",
    "Jimmy DURMAZ",
    "JO Hyeonwoo",
    "JOAO MARIO",
    "JOAO MOUTINHO",
    "Joel CAMPBELL",
    "Joel OBI",
    "Johan DJOUROU",
    "Johan MOJICA",
    "Johan VENEGAS",
    "Johann GUDMUNDSSON",
    "John GUIDETTI",
    "John Obi MIKEL",
    "John OGU",
    "John STONES",
    "Johnny ACOSTA",
    "Jon BODVARSSON",
    "Jonas HECTOR",
    "Jonas KNUDSEN",
    "Jonas LOSSL",
    "Jonathan DOS SANTOS",
    "Jonathan URRETAVISCAYA",
    "Jordan HENDERSON",
    "Jordan PICKFORD",
    "Jordi ALBA",
    "Jose CALDERON",
    "Jose CARVALLO",
    "Jose CORONA",
    "Jose CUADRADO",
    "JOSE FONTE",
    "Jose GIMENEZ",
    "Jose IZQUIERDO",
    "Jose Luis RODRIGUEZ",
    "Joshua KIMMICH",
    "Joshua RISDON",
    "Josip DRMIC",
    "Josip PIVARIC",
    "JU Sejong",
    "Juan CUADRADO",
    "Juan QUINTERO",
    "Julian BRANDT",
    "Julian DRAXLER",
    "JUNG Seunghyun",
    "JUNG Wooyoung",
    "KAHRABA",
    "Kalidou KOULIBALY",
    "Kamil GLIK",
    "Kamil GROSICKI",
    "Kara MBODJI",
    "Kari ARNASON",
    "Karim ANSARIFARD",
    "Karim EL AHMADI",
    "Karl-Johan JOHNSSON",
    "Karol LINETTY",
    "Kasper  SCHMEICHEL",
    "Kasper DOLBERG",
    "Keisuke HONDA",
    "Keita BALDE",
    "Kelechi IHEANACHO",
    "Kendall WASTON",
    "Kenner GUTIERREZ",
    "Kenneth OMERUO",
    "Kepa ARRIZABALAGA",
    "Kevin DE BRUYNE",
    "Kevin TRAPP",
    "Keylor NAVAS",
    "Khadim NDIAYE",
    "Khalid BOUTAIB",
    "KI Sungyueng",
    "Kieran TRIPPIER",
    "KIM Jinhyeon",
    "KIM Minwoo",
    "KIM Seunggyu",
    "KIM Shinwook",
    "KIM Younggwon",
    "Koen CASTEELS",
    "KOKE",
    "KOO Jacheol",
    "Kosuke NAKAMURA",
    "Kristoffer NORDFELDT",
    "Kyle WALKER",
    "Kylian MBAPPE",
    "Lamine GASSAMA",
    "Lasse SCHONE",
    "Leander DENDONCKER",
    "LEE Jaesung",
    "LEE Seungwoo",
    "LEE Yong",
    "Leon BALOGUN",
    "Leon GORETZKA",
    "Leonel MOREIRA",
    "Lionel MESSI",
    "Lovre KALINIC",
    "Lucas BIGLIA",
    "Lucas HERNANDEZ",
    "Lucas TORREIRA",
    "Lucas VAZQUEZ",
    "Ludwig AUGUSTINSSON",
    "Luis ADVINCULA",
    "Luis MURIEL",
    "Luis OVALLE",
    "Luis SUAREZ",
    "Luis TEJADA",
    "Luka JOVIC",
    "Luka MILIVOJEVIC",
    "Luka MODRIC",
    "Lukas LERAGER",
    "Lukasz FABIANSKI",
    "Lukasz PISZCZEK",
    "Lukasz TEODORCZYK",
    "Maciej RYBUS",
    "Mahdi TORABI",
    "MAHMOUD HAMDY",
    "Majid HOSSEINI",
    "Makoto HASEBE",
    "Mame DIOUF",
    "MANSOUR ALHARBI",
    "Manuel AKANJI",
    "Manuel DA COSTA",
    "MANUEL FERNANDES",
    "Manuel NEUER",
    "Marc-Andre TER STEGEN",
    "MARCELO",
    "Marcelo BROZOVIC",
    "Marco ASENSIO",
    "Marco FABIAN",
    "Marco REUS",
    "Marcos ACUNA",
    "Marcos ROJO",
    "Marcos URENA",
    "Marcus BERG",
    "Marcus RASHFORD",
    "Marcus ROHDEN",
    "MARIO FERNANDES",
    "Mario GAVRANOVIC",
    "Mario GOMEZ",
    "Mario MANDZUKIC",
    "MARIO RUI",
    "Mark MILLIGAN",
    "Marko DMITROVIC",
    "Marko GRUJIC",
    "Marko PJACA",
    "Marouane FELLAINI",
    "MARQUINHOS",
    "Martin BRAITHWAITE",
    "Martin CACERES",
    "Martin CAMPANA",
    "Martin OLSSON",
    "Martin SILVA",
    "Marvin PLATTENHARDT",
    "MARWAN MOHSEN",
    "Masaaki HIGASHIGUCHI",
    "Masoud SHOJAEI",
    "Massimo LUONGO",
    "Mateo KOVACIC",
    "Mateus URIBE",
    "Mathew LECKIE",
    "Mathew RYAN",
    "Mathias  JORGENSEN",
    "Matias VECINO",
    "Mats HUMMELS",
    "Matthew JURMAN",
    "Matthias GINTER",
    "Maximiliano GOMEZ",
    "Maximiliano MEZA",
    "Maximiliano PEREIRA",
    "Maya YOSHIDA",
    "Mbark BOUSSOUFA",
    "Mbaye NIANG",
    "Mehdi BENATIA",
    "Mehdi CARCELA",
    "Mehdi TAREMI",
    "Mesut OEZIL",
    "Michael KROHN-DEHLI",
    "Michael LANG",
    "Michael MURILLO",
    "Michal PAZDAN",
    "Michy BATSHUAYI",
    "Miguel ARAUJO",
    "Miguel BORJA",
    "Miguel LAYUN",
    "Miguel TRAUCO",
    "Mikael LUSTIG",
    "Milad MOHAMMADI",
    "Milan BADELJ",
    "Milan RODIC",
    "Mile JEDINAK",
    "Milos DEGENEK",
    "Milos VELJKOVIC",
    "MIRANDA",
    "MOHAMED ABDELSHAFY",
    "Mohamed BEN AMOR",
    "MOHAMED ELNENY",
    "MOHAMED ELSHENAWY",
    "MOHAMED KANNO",
    "MOHAMED SALAH",
    "Mohammad Reza KHANZADEH",
    "MOHAMMED ALBURAYK",
    "MOHAMMED ALOWAIS",
    "MOHAMMED ALSAHLAWI",
    "Monir EL KAJOUI",
    "MOON Seonmin",
    "Morteza POURALIGANJI",
    "MOTAZ HAWSAWI",
    "Mouez HASSEN",
    "Moussa DEMBELE",
    "Moussa KONATE",
    "Moussa SOW",
    "Moussa WAGUE",
    "MUHANNAD ASIRI",
    "Nabil DIRAR",
    "Nabil FEKIR",
    "Nacer CHADLI",
    "NACHO",
    "Nacho MONREAL",
    "Nahitan NANDEZ",
    "Nahuel GUZMAN",
    "Naim SLITI",
    "Naomichi UEDA",
    "Nemanja MATIC",
    "Nemanja RADONJIC",
    "NEYMAR",
    "Ngolo KANTE",
    "Nick POPE",
    "Nico ELVEDI",
    "Nicolai JORGENSEN",
    "Nicolas OTAMENDI",
    "Nicolas TAGLIAFICO",
    "Niklas SUELE",
    "Nikola KALINIC",
    "Nikola MILENKOVIC",
    "Nilson LOYOLA",
    "Noureddine AMRABAT",
    "Odion IGHALO",
    "Ogenyi ONAZI",
    "Oghenekaro ETEBO",
    "OH Bansuk",
    "Ola TOIVONEN",
    "Olafur SKULASON",
    "Olivier GIROUD",
    "OMAR GABER",
    "OMAR HAWSAWI",
    "Omid EBRAHIMI",
    "Oribe PERALTA",
    "OSAMA HAWSAWI",
    "Oscar DUARTE",
    "Oscar HILJEMARK",
    "Oscar MURILLO",
    "Ousmane DEMBELE",
    "Oussama HADDADI",
    "Paolo GUERRERO",
    "Paolo HURTADO",
    "Pape Alioune NDIAYE",
    "PARK Jooho",
    "Patrick PEMBERTON",
    "Paul POGBA",
    "PAULINHO",
    "Paulo DYBALA",
    "Pedro AQUINO",
    "Pedro GALLESE",
    "PEDRO GEROMEL",
    "Pejman MONTAZERI",
    "PEPE",
    "Pepe REINA",
    "Phil JONES",
    "PHILIPPE COUTINHO",
    "Pione SISTO",
    "Piotr ZIELINSKI",
    "Pontus JANSSON",
    "Predrag RAJKOVIC",
    "Presnel KIMPEMBE",
    "Radamel FALCAO",
    "Rafael MARQUEZ",
    "Rafal KURZAWA",
    "Ragnar SIGURDSSON",
    "Raheem STERLING",
    "RAMADAN SOBHY",
    "Rami BEDOUI",
    "Ramin REZAEIAN",
    "Randall AZOFEIFA",
    "RAPHAEL GUERREIRO",
    "Raphael VARANE",
    "Rashid MAZAHERI",
    "Raul JIMENEZ",
    "Raul RUIDIAZ",
    "Remo FREULER",
    "RENATO AUGUSTO",
    "Renato TAPIA",
    "Reza GHOOCHANNEJHAD",
    "RICARDO",
    "Ricardo AVILA",
    "RICARDO QUARESMA",
    "Ricardo RODRIGUEZ",
    "Robbie KRUSE",
    "Robert LEWANDOWSKI",
    "ROBERTO FIRMINO",
    "Robin OLSEN",
    "Rodney WALLACE",
    "RODRIGO",
    "Rodrigo BENTANCUR",
    "Roman BUERKI",
    "Roman TORRES",
    "Roman ZOBNIN",
    "Romelu LUKAKU",
    "Roozbeh CHESHMI",
    "RUBEN DIAS",
    "Ruben LOFTUS-CHEEK",
    "RUI PATRICIO",
    "Runar RUNARSSON",
    "Rurik GISLASON",
    "Ryota OHSHIMA",
    "Saber KHALIFA",
    "Sadio MANE",
    "Saeid EZATOLAHI",
    "Saifeddine KHAOUI",
    "SALEM ALDAWSARI",
    "Salif SANE",
    "SALMAN ALFARAJ",
    "SAM MORSY",
    "Saman GHODDOS",
    "Sami KHEDIRA",
    "SAMIR SAAD",
    "Samuel FRIDJONSSON",
    "Samuel UMTITI",
    "Santiago ARIAS",
    "Sardar AZMOUN",
    "SAUL",
    "Sebastian COATES",
    "Sebastian LARSSON",
    "Sebastian RUDY",
    "Sergej MILINKOVIC-SAVIC",
    "Sergey IGNASHEVICH",
    "Sergio AGUERO",
    "Sergio BUSQUETS",
    "Sergio RAMOS",
    "SHERIF EKRAMY",
    "SHIKABALA",
    "Shinji KAGAWA",
    "Shinji OKAZAKI",
    "Sime VRSALJKO",
    "Simeon NWANKWO",
    "Simon KJAER",
    "Simon MIGNOLET",
    "Slawomir PESZKO",
    "Sofyan AMRABAT",
    "SON Heungmin",
    "Stephan LICHTSTEINER",
    "Steve MANDANDA",
    "Steven NZONZI",
    "Steven ZUBER",
    "Sverrir INGASON",
    "Syam BEN YOUSSEF",
    "TAISEER ALJASSAM",
    "TAISON",
    "Takashi INUI",
    "Takashi USAMI",
    "TAREK HAMED",
    "THIAGO",
    "Thiago CIONEK",
    "THIAGO SILVA",
    "Thibaut COURTOIS",
    "Thomas DELANEY",
    "Thomas LEMAR",
    "Thomas MEUNIER",
    "Thomas MUELLER",
    "Thomas VERMAELEN",
    "Thorgan HAZARD",
    "Tim CAHILL",
    "Timo WERNER",
    "Tin JEDVAJ",
    "Toby ALDERWEIRELD",
    "Tom ROGIC",
    "Tomi JURIC",
    "Tomoaki MAKINO",
    "Toni KROOS",
    "Trent ALEXANDER-ARNOLD",
    "Trent SAINSBURY",
    "TREZIGUET",
    "Tyronne EBUEHI",
    "Uros SPAJIC",
    "Vahid AMIRI",
    "Valentin PIMENTEL",
    "Valon BEHRAMI",
    "Vedran CORLUKA",
    "Victor LINDELOF",
    "Victor MOSES",
    "Viktor CLAESSON",
    "Viktor FISCHER",
    "Vincent KOMPANY",
    "Vladimir GABULOV",
    "Vladimir GRANAT",
    "Vladimir STOJKOVIC",
    "Wahbi KHAZRI",
    "Wataru ENDO",
    "Wilder CARTAGENA",
    "Wilfred NDIDI",
    "Wilfredo CABALLERO",
    "WILLIAM",
    "William EKONG",
    "William KVIST",
    "WILLIAN",
    "Wilmar BARRIOS",
    "Wojciech SZCZESNY",
    "Xherdan SHAQIRI",
    "YAHIA ALSHEHRI",
    "Yann SOMMER",
    "Yannick CARRASCO",
    "YASSER ALMOSAILEM",
    "YASSER ALSHAHRANI",
    "Yassine BOUNOU",
    "Yassine MERIAH",
    "Yeltsin TEJEDA",
    "Yerry MINA",
    "Yohan BEN ALOUANE",
    "Yoshimar YOTUN",
    "Yoshinori MUTO",
    "Younes BELHANDA",
    "Youri TIELEMANS",
    "Youssef AIT BENNASSER",
    "Youssef EN NESYRI",
    "Youssouf SABALY",
    "YUN Youngsun",
    "Yury ZHIRKOV",
    "Yussuf Yurary POULSEN",
    "Yuto NAGATOMO",
    "Yuya OSAKO",
    "Yvon MVOGO",
    "Manuel NEUER",
    "Kevin TRAPP",
    "Marc-Andre TER STEGEN",
    "Marvin PLATTENHARDT",
    "Jonas HECTOR",
    "Matthias GINTER",
    "Mats HUMMELS",
    "Niklas SUELE",
    "Antonio RUEDIGER",
    "Jerome BOATENG",
    "Joshua KIMMICH",
    "Sami KHEDIRA",
    "Julian DRAXLER",
    "Toni KROOS",
    "Mesut OEZIL",
    "Thomas MUELLER",
    "Leon GORETZKA",
    "Sebastian RUDY",
    "Julian BRANDT",
    "Ilkay GUENDOGAN",
    "Timo WERNER",
    "Marco REUS",
    "Mario GOMEZ",
  ]

  const playerNumbers = [
    "13",
    "19",
    "16",
    "1",
    "15",
    "1",
    "14",
    "12",
    "11",
    "8",
    "2",
    "2",
    "22",
    "17",
    "18",
    "13",
    "23",
    "3",
    "7",
    "6",
    "15",
    "7",
    "22",
    "9",
    "4",
    "2",
    "8",
    "3",
    "11",
    "9",
    "8",
    "21",
    "17",
    "18",
    "22",
    "19",
    "15",
    "11",
    "23",
    "13",
    "12",
    "4",
    "1",
    "2",
    "12",
    "18",
    "1",
    "23",
    "12",
    "18",
    "22",
    "22",
    "4",
    "18",
    "9",
    "6",
    "21",
    "4",
    "12",
    "9",
    "18",
    "6",
    "11",
    "5",
    "7",
    "14",
    "11",
    "20",
    "9",
    "18",
    "12",
    "7",
    "16",
    "16",
    "2",
    "23",
    "7",
    "11",
    "21",
    "17",
    "22",
    "3",
    "21",
    "18",
    "6",
    "12",
    "16",
    "9",
    "16",
    "20",
    "18",
    "12",
    "18",
    "22",
    "2",
    "11",
    "22",
    "8",
    "2",
    "9",
    "14",
    "7",
    "15",
    "12",
    "6",
    "7",
    "2",
    "16",
    "2",
    "8",
    "10",
    "12",
    "7",
    "12",
    "3",
    "6",
    "5",
    "11",
    "5",
    "16",
    "21",
    "5",
    "14",
    "11",
    "8",
    "20",
    "7",
    "8",
    "10",
    "15",
    "12",
    "11",
    "4",
    "16",
    "22",
    "7",
    "2",
    "7",
    "7",
    "2",
    "16",
    "17",
    "9",
    "23",
    "14",
    "3",
    "18",
    "14",
    "1",
    "20",
    "1",
    "21",
    "23",
    "23",
    "20",
    "6",
    "20",
    "6",
    "17",
    "15",
    "19",
    "3",
    "17",
    "21",
    "19",
    "21",
    "1",
    "7",
    "14",
    "15",
    "10",
    "3",
    "11",
    "10",
    "23",
    "8",
    "21",
    "20",
    "21",
    "18",
    "3",
    "1",
    "3",
    "17",
    "10",
    "20",
    "16",
    "15",
    "4",
    "15",
    "5",
    "1",
    "7",
    "17",
    "22",
    "22",
    "19",
    "8",
    "18",
    "1",
    "11",
    "6",
    "13",
    "10",
    "23",
    "13",
    "17",
    "1",
    "4",
    "14",
    "14",
    "17",
    "6",
    "20",
    "23",
    "15",
    "12",
    "3",
    "18",
    "22",
    "12",
    "6",
    "9",
    "2",
    "9",
    "7",
    "15",
    "13",
    "16",
    "18",
    "3",
    "8",
    "3",
    "6",
    "20",
    "3",
    "10",
    "10",
    "20",
    "22",
    "17",
    "9",
    "21",
    "10",
    "10",
    "13",
    "4",
    "13",
    "10",
    "7",
    "21",
    "3",
    "1",
    "9",
    "3",
    "9",
    "6",
    "9",
    "16",
    "15",
    "14",
    "19",
    "22",
    "15",
    "14",
    "18",
    "16",
    "2",
    "1",
    "16",
    "11",
    "17",
    "4",
    "5",
    "1",
    "23",
    "1",
    "21",
    "3",
    "22",
    "22",
    "10",
    "18",
    "8",
    "4",
    "7",
    "3",
    "6",
    "13",
    "22",
    "1",
    "16",
    "3",
    "10",
    "14",
    "11",
    "5",
    "5",
    "20",
    "3",
    "20",
    "14",
    "14",
    "16",
    "10",
    "17",
    "17",
    "7",
    "17",
    "23",
    "21",
    "23",
    "10",
    "8",
    "12",
    "15",
    "20",
    "17",
    "11",
    "7",
    "11",
    "10",
    "19",
    "5",
    "2",
    "22",
    "3",
    "5",
    "16",
    "6",
    "20",
    "8",
    "1",
    "18",
    "12",
    "21",
    "1",
    "22",
    "6",
    "2",
    "21",
    "21",
    "18",
    "19",
    "19",
    "22",
    "8",
    "11",
    "20",
    "20",
    "7",
    "3",
    "15",
    "11",
    "3",
    "15",
    "11",
    "4",
    "14",
    "10",
    "8",
    "12",
    "8",
    "1",
    "12",
    "4",
    "20",
    "14",
    "19",
    "22",
    "22",
    "13",
    "7",
    "12",
    "1",
    "16",
    "13",
    "16",
    "12",
    "21",
    "12",
    "1",
    "9",
    "19",
    "13",
    "8",
    "13",
    "23",
    "23",
    "2",
    "10",
    "21",
    "19",
    "23",
    "17",
    "10",
    "2",
    "6",
    "14",
    "23",
    "10",
    "12",
    "5",
    "21",
    "14",
    "11",
    "6",
    "17",
    "14",
    "17",
    "9",
    "18",
    "19",
    "4",
    "10",
    "18",
    "22",
    "20",
    "14",
    "13",
    "2",
    "15",
    "19",
    "17",
    "9",
    "2",
    "5",
    "4",
    "4",
    "1",
    "22",
    "12",
    "11",
    "20",
    "8",
    "11",
    "8",
    "16",
    "21",
    "9",
    "19",
    "19",
    "2",
    "18",
    "23",
    "17",
    "19",
    "5",
    "23",
    "16",
    "20",
    "8",
    "13",
    "11",
    "22",
    "12",
    "5",
    "23",
    "2",
    "9",
    "12",
    "7",
    "8",
    "8",
    "15",
    "7",
    "1",
    "13",
    "15",
    "5",
    "6",
    "4",
    "18",
    "13",
    "16",
    "22",
    "14",
    "19",
    "5",
    "23",
    "17",
    "10",
    "2",
    "6",
    "2",
    "2",
    "21",
    "5",
    "19",
    "7",
    "6",
    "2",
    "5",
    "19",
    "14",
    "15",
    "2",
    "13",
    "3",
    "13",
    "14",
    "17",
    "23",
    "12",
    "10",
    "13",
    "6",
    "22",
    "10",
    "12",
    "18",
    "8",
    "23",
    "22",
    "19",
    "14",
    "7",
    "22",
    "20",
    "17",
    "18",
    "22",
    "4",
    "16",
    "8",
    "1",
    "23",
    "2",
    "21",
    "18",
    "10",
    "13",
    "23",
    "4",
    "9",
    "17",
    "3",
    "15",
    "16",
    "15",
    "22",
    "16",
    "9",
    "17",
    "8",
    "4",
    "20",
    "16",
    "9",
    "4",
    "5",
    "9",
    "19",
    "3",
    "6",
    "15",
    "3",
    "11",
    "5",
    "9",
    "7",
    "17",
    "6",
    "18",
    "6",
    "15",
    "21",
    "23",
    "1",
    "4",
    "15",
    "3",
    "23",
    "16",
    "11",
    "23",
    "19",
    "18",
    "12",
    "3",
    "9",
    "4",
    "21",
    "6",
    "10",
    "14",
    "6",
    "23",
    "14",
    "5",
    "4",
    "12",
    "9",
    "11",
    "8",
    "8",
    "13",
    "16",
    "15",
    "19",
    "20",
    "13",
    "10",
    "9",
    "20",
    "1",
    "13",
    "9",
    "6",
    "21",
    "5",
    "11",
    "9",
    "4",
    "13",
    "21",
    "1",
    "13",
    "19",
    "18",
    "19",
    "10",
    "6",
    "7",
    "18",
    "6",
    "7",
    "5",
    "14",
    "6",
    "20",
    "3",
    "5",
    "4",
    "20",
    "7",
    "19",
    "7",
    "19",
    "20",
    "4",
    "19",
    "5",
    "15",
    "16",
    "18",
    "10",
    "9",
    "2",
    "13",
    "4",
    "12",
    "17",
    "21",
    "7",
    "2",
    "16",
    "15",
    "14",
    "5",
    "2",
    "17",
    "21",
    "14",
    "11",
    "8",
    "10",
    "4",
    "2",
    "1",
    "8",
    "8",
    "15",
    "13",
    "3",
    "16",
    "4",
    "9",
    "13",
    "2",
    "23",
    "9",
    "20",
    "8",
    "22",
    "20",
    "21",
    "21",
    "5",
    "11",
    "14",
    "11",
    "5",
    "3",
    "11",
    "17",
    "15",
    "4",
    "20",
    "14",
    "1",
    "10",
    "6",
    "16",
    "4",
    "23",
    "14",
    "5",
    "7",
    "19",
    "5",
    "1",
    "23",
    "8",
    "1",
    "11",
    "21",
    "13",
    "1",
    "4",
    "17",
    "13",
    "3",
    "19",
    "13",
    "10",
    "17",
    "15",
    "19",
    "12",
    "5",
    "18",
    "20",
    "5",
    "15",
    "12",
    "1",
    "12",
    "22",
    "2",
    "3",
    "4",
    "5",
    "15",
    "16",
    "17",
    "18",
    "6",
    "7",
    "8",
    "10",
    "13",
    "14",
    "19",
    "20",
    "21",
    "9",
    "11",
    "23"
  ]

  const playerCountries = [
    "Australia",
    "Egipto",
    "Panamá",
    "Senegal",
    "Arabia Saudí",
    "Arabia Saudí",
    "Arabia Saudí",
    "Nigeria",
    "Arabia Saudí",
    "Colombia",
    "Marruecos",
    "Senegal",
    "Serbia",
    "Francia",
    "Bélgica",
    "Panamá",
    "Portugal",
    "Egipto",
    "Egipto",
    "Egipto",
    "Túnez",
    "Nigeria",
    "Marruecos",
    "Rusia",
    "Islandia",
    "Perú",
    "Suecia",
    "Perú",
    "Serbia",
    "Serbia",
    "Serbia",
    "Rusia",
    "Rusia",
    "Nigeria",
    "Panamá",
    "Rusia",
    "Rusia",
    "Islandia",
    "Senegal",
    "Senegal",
    "México",
    "Arabia Saudí",
    "RI de Irán",
    "Egipto",
    "Túnez",
    "RI de Irán",
    "Brasil",
    "Francia",
    "España",
    "Marruecos",
    "RI de Irán",
    "Egipto",
    "Perú",
    "Perú",
    "Portugal",
    "Dinamarca",
    "Dinamarca",
    "Suecia",
    "Rusia",
    "Croacia",
    "México",
    "España",
    "Australia",
    "Rusia",
    "Serbia",
    "Perú",
    "Argentina",
    "Panamá",
    "Túnez",
    "Croacia",
    "Portugal",
    "Francia",
    "Rusia",
    "Alemania",
    "Serbia",
    "Islandia",
    "Polonia",
    "Panamá",
    "Islandia",
    "Islandia",
    "Rusia",
    "Polonia",
    "RI de Irán",
    "Inglaterra",
    "Bélgica",
    "Egipto",
    "Túnez",
    "Marruecos",
    "Australia",
    "Marruecos",
    "Polonia",
    "Polonia",
    "Túnez",
    "Francia",
    "Francia",
    "Portugal",
    "Portugal",
    "Islandia",
    "Islandia",
    "Islandia",
    "Francia",
    "Panamá",
    "Suiza",
    "Australia",
    "Serbia",
    "Suiza",
    "Portugal",
    "Portugal",
    "Nigeria",
    "Costa Rica",
    "Costa Rica",
    "Colombia",
    "Colombia",
    "Perú",
    "México",
    "Colombia",
    "Uruguay",
    "México",
    "Brasil",
    "Brasil",
    "Portugal",
    "Costa Rica",
    "España",
    "Senegal",
    "Senegal",
    "Nigeria",
    "Costa Rica",
    "Perú",
    "Dinamarca",
    "Perú",
    "Francia",
    "Uruguay",
    "Argentina",
    "Costa Rica",
    "Argentina",
    "Uruguay",
    "Colombia",
    "Portugal",
    "Rusia",
    "España",
    "Nigeria",
    "Australia",
    "Costa Rica",
    "Croacia",
    "Brasil",
    "Inglaterra",
    "Australia",
    "Inglaterra",
    "España",
    "Costa Rica",
    "Colombia",
    "España",
    "Colombia",
    "Polonia",
    "Bélgica",
    "Croacia",
    "Inglaterra",
    "Rusia",
    "Suiza",
    "Senegal",
    "España",
    "Uruguay",
    "Uruguay",
    "Australia",
    "Francia",
    "Croacia",
    "Croacia",
    "Brasil",
    "Bélgica",
    "Croacia",
    "Serbia",
    "Serbia",
    "Túnez",
    "Bélgica",
    "Brasil",
    "Panamá",
    "Uruguay",
    "Perú",
    "México",
    "Argentina",
    "RI de Irán",
    "Japón",
    "Nigeria",
    "Túnez",
    "Suecia",
    "Islandia",
    "Suecia",
    "Argentina",
    "Inglaterra",
    "Panamá",
    "México",
    "Egipto",
    "Argentina",
    "Inglaterra",
    "Suiza",
    "Brasil",
    "Arabia Saudí",
    "Túnez",
    "Colombia",
    "Túnez",
    "Marruecos",
    "Argentina",
    "Rusia",
    "Rusia",
    "Panamá",
    "Túnez",
    "Brasil",
    "Uruguay",
    "Panamá",
    "Croacia",
    "Suecia",
    "Serbia",
    "Brasil",
    "Francia",
    "Nigeria",
    "Costa Rica",
    "Argentina",
    "Suiza",
    "Brasil",
    "Dinamarca",
    "Islandia",
    "Panamá",
    "Brasil",
    "Argentina",
    "Panamá",
    "Japón",
    "Inglaterra",
    "Uruguay",
    "Suiza",
    "Portugal",
    "Japón",
    "Japón",
    "España",
    "Marruecos",
    "Túnez",
    "Costa Rica",
    "Uruguay",
    "México",
    "Argentina",
    "República de Corea",
    "Portugal",
    "Argentina",
    "Japón",
    "Suiza",
    "Polonia",
    "México",
    "Uruguay",
    "Suecia",
    "Islandia",
    "Marruecos",
    "Túnez",
    "Marruecos",
    "Islandia",
    "Suiza",
    "Panamá",
    "Inglaterra",
    "Inglaterra",
    "Arabia Saudí",
    "México",
    "México",
    "Dinamarca",
    "Japón",
    "México",
    "Islandia",
    "República de Corea",
    "Islandia",
    "Japón",
    "México",
    "Francia",
    "Arabia Saudí",
    "República de Corea",
    "España",
    "Costa Rica",
    "Senegal",
    "Rusia",
    "Rusia",
    "Nigeria",
    "Alemania",
    "Rusia",
    "Suecia",
    "España",
    "Panamá",
    "Senegal",
    "Rusia",
    "Croacia",
    "Croacia",
    "Croacia",
    "Polonia",
    "Inglaterra",
    "Australia",
    "Panamá",
    "Polonia",
    "Australia",
    "Colombia",
    "Australia",
    "Inglaterra",
    "Polonia",
    "Bélgica",
    "República de Corea",
    "Dinamarca",
    "México",
    "México",
    "Argentina",
    "Colombia",
    "Perú",
    "Dinamarca",
    "Alemania",
    "Inglaterra",
    "México",
    "México",
    "Suecia",
    "República de Corea",
    "Portugal",
    "Portugal",
    "Costa Rica",
    "Nigeria",
    "Suiza",
    "Colombia",
    "Costa Rica",
    "Islandia",
    "Suecia",
    "Nigeria",
    "Nigeria",
    "Inglaterra",
    "Costa Rica",
    "Islandia",
    "Alemania",
    "Dinamarca",
    "Dinamarca",
    "México",
    "Uruguay",
    "Inglaterra",
    "Inglaterra",
    "España",
    "Panamá",
    "Perú",
    "México",
    "Colombia",
    "Portugal",
    "Uruguay",
    "Colombia",
    "Panamá",
    "Alemania",
    "Australia",
    "Suiza",
    "Croacia",
    "República de Corea",
    "Colombia",
    "Colombia",
    "Alemania",
    "Alemania",
    "República de Corea",
    "República de Corea",
    "Egipto",
    "Senegal",
    "Polonia",
    "Polonia",
    "Senegal",
    "Islandia",
    "RI de Irán",
    "Marruecos",
    "Suecia",
    "Polonia",
    "Dinamarca",
    "Dinamarca",
    "Japón",
    "Senegal",
    "Nigeria",
    "Costa Rica",
    "Costa Rica",
    "Nigeria",
    "España",
    "Bélgica",
    "Alemania",
    "Costa Rica",
    "Senegal",
    "Marruecos",
    "República de Corea",
    "Inglaterra",
    "República de Corea",
    "República de Corea",
    "República de Corea",
    "República de Corea",
    "República de Corea",
    "Bélgica",
    "España",
    "República de Corea",
    "Japón",
    "Suecia",
    "Inglaterra",
    "Francia",
    "Senegal",
    "Dinamarca",
    "Bélgica",
    "República de Corea",
    "República de Corea",
    "República de Corea",
    "Nigeria",
    "Alemania",
    "Costa Rica",
    "Argentina",
    "Croacia",
    "Argentina",
    "Francia",
    "Uruguay",
    "España",
    "Suecia",
    "Perú",
    "Colombia",
    "Panamá",
    "Uruguay",
    "Panamá",
    "Serbia",
    "Serbia",
    "Croacia",
    "Dinamarca",
    "Polonia",
    "Polonia",
    "Polonia",
    "Polonia",
    "RI de Irán",
    "Egipto",
    "RI de Irán",
    "Japón",
    "Senegal",
    "Arabia Saudí",
    "Suiza",
    "Marruecos",
    "Portugal",
    "Alemania",
    "Alemania",
    "Brasil",
    "Croacia",
    "España",
    "México",
    "Alemania",
    "Argentina",
    "Argentina",
    "Costa Rica",
    "Suecia",
    "Inglaterra",
    "Suecia",
    "Rusia",
    "Suiza",
    "Alemania",
    "Croacia",
    "Portugal",
    "Australia",
    "Serbia",
    "Serbia",
    "Croacia",
    "Bélgica",
    "Brasil",
    "Dinamarca",
    "Uruguay",
    "Uruguay",
    "Suecia",
    "Uruguay",
    "Alemania",
    "Egipto",
    "Japón",
    "RI de Irán",
    "Australia",
    "Croacia",
    "Colombia",
    "Australia",
    "Australia",
    "Dinamarca",
    "Uruguay",
    "Alemania",
    "Australia",
    "Alemania",
    "Uruguay",
    "Argentina",
    "Uruguay",
    "Japón",
    "Marruecos",
    "Senegal",
    "Marruecos",
    "Marruecos",
    "RI de Irán",
    "Alemania",
    "Dinamarca",
    "Suiza",
    "Panamá",
    "Polonia",
    "Bélgica",
    "Perú",
    "Colombia",
    "México",
    "Perú",
    "Suecia",
    "RI de Irán",
    "Croacia",
    "Serbia",
    "Australia",
    "Australia",
    "Serbia",
    "Brasil",
    "Egipto",
    "Túnez",
    "Egipto",
    "Egipto",
    "Arabia Saudí",
    "Egipto",
    "RI de Irán",
    "Arabia Saudí",
    "Arabia Saudí",
    "Arabia Saudí",
    "Marruecos",
    "República de Corea",
    "RI de Irán",
    "Arabia Saudí",
    "Túnez",
    "Bélgica",
    "Senegal",
    "Senegal",
    "Senegal",
    "Arabia Saudí",
    "Marruecos",
    "Francia",
    "Bélgica",
    "España",
    "España",
    "Uruguay",
    "Argentina",
    "Túnez",
    "Japón",
    "Serbia",
    "Serbia",
    "Brasil",
    "Francia",
    "Inglaterra",
    "Suiza",
    "Dinamarca",
    "Argentina",
    "Argentina",
    "Alemania",
    "Croacia",
    "Serbia",
    "Perú",
    "Marruecos",
    "Nigeria",
    "Nigeria",
    "Nigeria",
    "República de Corea",
    "Suecia",
    "Islandia",
    "Francia",
    "Egipto",
    "Arabia Saudí",
    "RI de Irán",
    "México",
    "Arabia Saudí",
    "Costa Rica",
    "Suecia",
    "Colombia",
    "Francia",
    "Túnez",
    "Perú",
    "Perú",
    "Senegal",
    "República de Corea",
    "Costa Rica",
    "Francia",
    "Brasil",
    "Argentina",
    "Perú",
    "Perú",
    "Brasil",
    "RI de Irán",
    "Portugal",
    "España",
    "Inglaterra",
    "Brasil",
    "Dinamarca",
    "Polonia",
    "Suecia",
    "Serbia",
    "Francia",
    "Colombia",
    "México",
    "Polonia",
    "Islandia",
    "Inglaterra",
    "Egipto",
    "Túnez",
    "RI de Irán",
    "Costa Rica",
    "Portugal",
    "Francia",
    "RI de Irán",
    "México",
    "Perú",
    "Suiza",
    "Brasil",
    "Perú",
    "RI de Irán",
    "Portugal",
    "Panamá",
    "Portugal",
    "Suiza",
    "Australia",
    "Polonia",
    "Brasil",
    "Suecia",
    "Costa Rica",
    "España",
    "Uruguay",
    "Suiza",
    "Panamá",
    "Rusia",
    "Bélgica",
    "RI de Irán",
    "Portugal",
    "Inglaterra",
    "Portugal",
    "Islandia",
    "Islandia",
    "Japón",
    "Túnez",
    "Senegal",
    "RI de Irán",
    "Túnez",
    "Arabia Saudí",
    "Senegal",
    "Arabia Saudí",
    "Egipto",
    "RI de Irán",
    "Alemania",
    "Egipto",
    "Islandia",
    "Francia",
    "Colombia",
    "RI de Irán",
    "España",
    "Uruguay",
    "Suecia",
    "Alemania",
    "Serbia",
    "Rusia",
    "Argentina",
    "España",
    "España",
    "Egipto",
    "Egipto",
    "Japón",
    "Japón",
    "Croacia",
    "Nigeria",
    "Dinamarca",
    "Bélgica",
    "Polonia",
    "Marruecos",
    "República de Corea",
    "Suiza",
    "Francia",
    "Francia",
    "Suiza",
    "Islandia",
    "Túnez",
    "Arabia Saudí",
    "Brasil",
    "Japón",
    "Japón",
    "Egipto",
    "España",
    "Polonia",
    "Brasil",
    "Bélgica",
    "Dinamarca",
    "Francia",
    "Bélgica",
    "Alemania",
    "Bélgica",
    "Bélgica",
    "Australia",
    "Alemania",
    "Croacia",
    "Bélgica",
    "Australia",
    "Australia",
    "Japón",
    "Alemania",
    "Inglaterra",
    "Australia",
    "Egipto",
    "Nigeria",
    "Serbia",
    "RI de Irán",
    "Panamá",
    "Suiza",
    "Croacia",
    "Suecia",
    "Nigeria",
    "Suecia",
    "Dinamarca",
    "Bélgica",
    "Rusia",
    "Rusia",
    "Serbia",
    "Túnez",
    "Japón",
    "Perú",
    "Nigeria",
    "Argentina",
    "Portugal",
    "Nigeria",
    "Dinamarca",
    "Brasil",
    "Colombia",
    "Polonia",
    "Suiza",
    "Arabia Saudí",
    "Suiza",
    "Bélgica",
    "Arabia Saudí",
    "Arabia Saudí",
    "Marruecos",
    "Túnez",
    "Costa Rica",
    "Colombia",
    "Túnez",
    "Perú",
    "Japón",
    "Marruecos",
    "Bélgica",
    "Marruecos",
    "Marruecos",
    "Senegal",
    "República de Corea",
    "Rusia",
    "Dinamarca",
    "Japón",
    "Japón",
    "Suiza",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania",
    "Alemania"
  ]

  const playerRoles = [
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Defensor",
    "Delantero",
    "Arquero",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Arquero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Defensor",
    "Arquero",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Arquero",
    "Delantero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Delantero",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Arquero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Arquero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Arquero",
    "Arquero",
    "Arquero",
    "Arquero",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Arquero",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Defensor",
    "Arquero",
    "Delantero",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Arquero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Delantero",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Delantero",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Arquero",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Arquero",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Delantero",
    "Delantero",
    "Delantero",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Arquero",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Defensor",
    "Arquero",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Delantero",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Arquero",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Delantero",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Arquero",
    "Delantero",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Mediocampista",
    "Arquero",
    "Mediocampista",
    "Arquero",
    "Defensor",
    "Arquero",
    "Defensor",
    "Mediocampista",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Delantero",
    "Defensor",
    "Delantero",
    "Arquero",
    "Arquero",
    "Arquero",
    "Arquero",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Defensor",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Mediocampista",
    "Delantero",
    "Delantero",
    "Delantero"
  ]

 const data = playerNames.map((name, idx) => ({name, country: playerCountries[idx], number: playerNumbers[idx], role:playerRoles[idx]}))
console.log(data);

 